#!/bin/sh

## hyphop ##

BIN=$0
PROG=`basename $0`
MNTD=/mnt

usage(){
    echo "$PROG - mount disk by label to $MNTD/*LABEL*

    USAGE: $PROG [ LABEL ]  - mount by label
	   $PROG            - show disks labels list
	   $PROG --list     - show mounted to $MNTD/*LABEL*

    LINKS:

        https://github.com/hyphop/linux-scripts-collection

    "
}

for i in "$@"; do
case "$i" in
    --help|-h)
    usage
    exit 0
    ;;
    --list|-l)
    df | grep "$MNTD"
    exit 0
    ;;
esac
done

permup(){

# need root perms
# or
# sudo ./sys_drop_cache

[ "$USER" != "root" ] && {
    echo "[i] sudo $BIN $@" >&2
    sudo "$BIN" "$@"
    exit 0
}
    return 1

}

LABEL="$1"

[ "$LABEL" ] || {
    permup "$@"
    blkid -s LABEL
    exit 0
}

##
LABEL=`basename "$LABEL"`

MNT=$MNTD/$LABEL
MOUNTED=

eval `blkid -l -t LABEL="$LABEL" -o export`


[ "$DEVNAME" ] || {
    permup "$@" && exit 0
    echo  "[e] LABEL: $LABEL not found" >&2
    exit 0
}

    MOUNTED=`grep "$DEVNAME " /proc/mounts`

[ "$MOUNTED" ] ||
    MOUNTED=`grep "$MNT " /proc/mounts`

[ "$MOUNTED" ] && {
    echo "[w] already mounted LABEL=$LABEL => $MNT" >&2
    echo $MOUNTED >&2
    exit 0
} 


permup "$@"

[ "$TYPE" = "vfat" ] && ARG="$ARG -o iocharset=utf8,codepage=866"

echo "[i] mount ($TYPE) LABEL=$LABEL $ARG $MNT" >&2
mount "LABEL=$LABEL" $ARG "$MNT"

